### ISSUE TITLE
[Projekt] Namenlose Representation fuer den Lambda Calculus

### ISSUE THREAD

**Issue by kritzcreek** [kritzcreek/PuC-WS20#3]
## Projektidee
Implementiert den symbolischen (tree-rewriting) Evaluator mittels einer namenlosen Repraesentation. Implementiert ihn fuer den Lambda Calculus + If + Let (keine rekursiven bindings).

## Praesentationsinhalte
Erlaeutert die Schwierigkeit der Capture-avoiding Substitution, und wie man sie mittels namenloser Repraesentation umgehen kann.

## Stichworte
- De-Brujin Indizes
- Locally Nameless

**Comment by denwae** [comment]
Ich und Jonathan werden das Projekt machen.
Dennis Wäckerle
Jonathan Michel

**Comment by kritzcreek** [comment]
@DennisWae Ich weiss nicht wie hilfreich dieser Blogpost ist (er benutzt Haskell), aber versuchen kann man es ja mal ;) https://boarders.github.io/posts/locally-nameless/
