### ISSUE TITLE
[Projekt] Parser Generatoren

### ISSUE THREAD

**Issue by kritzcreek** [kritzcreek/PuC-WS20#4]
## Projektidee
Implementiert einen Parser fuer Weasel mit einem Parsergenerator. Die Sprache und das Tool sind hierbei freigestellt. Ideal waere ANTLR mit Kotlin, aber es ist keine Pflicht.

## Praesentation
Beschreibt die Vor- und Nachteile eines Parser Generatoren im Vergleich zu unserem handgeschriebenen Parser.

Beschreibt den Unterschied zwischen Bottom-up und Top-down parsing.

## Stichworte
Parsergenerator
LR-Parser
Backus-Naur-Form

**Comment by yahyaguzide** [comment]
Wenn dieses Projekt noch frei ist würde ich das übernehmen

**Comment by Basel451** [comment]
Basel Hussein
