### ISSUE TITLE
[Projekt] Untereinander-Rekursive Definitionen

### ISSUE THREAD

**Issue by kritzcreek** [kritzcreek/PuC-WS20#5]
## Projekt
Implementiert untereinander Rekursive lets in Weasel.

## Praesentation
Beschreibt eure Implementierung, und welche Probleme ihr loesen musstet.

## Stichworte
Binding Group
Mutual Recursion

**Comment by bhilgers** [comment]
Wird bearbeitet von Marlon Krause und Benedikt Hilgers
