### ISSUE TITLE
[Projekt] Pretty printer

### ISSUE THREAD

**Issue by kritzcreek** [kritzcreek/PuC-WS20#6]
## Projekt
Implementiert einen Prettyprinter fuer Weasel oder eine Sprache eurer Wahl. Dieser sollte ein "sinnvolles" Layout waehlen, zu lange Ausdruecke sollten auf mehrere Zeilen gebrochen werden, und eingerueckt werden. Die minimale Menge an Klammern sollte verwendet werden.

## Praesentation
Beschreibt die Aufgabe und was die Schwierigkeit im Prettyprinting ausmacht
Beschreibt eure Implementierung
(Wenn ihr moegt beschreibt einen Pretty printing Algorithmus)

## Stichworte
Prettyprinting
"A prettier printer" - Philip Wadler

**Comment by Dominkik302** [comment]
Timo Pritzkau, Dominik Dick und Marvin Herhaus
